### PR TITLE
Add some initial benchmarks

### PR DESCRIPTION
**Pull request by johnynek**
Well, this is not great:

```
[info] Benchmark                                Mode  Cnt       Score       Error  Units
[info] CollectionBenchmarks.find                avgt    5   40104.368 ±  3079.524  us/op
[info] CollectionBenchmarks.findInline          avgt    5   45389.999 ±  8223.375  us/op
[info] CollectionBenchmarks.reduceOption        avgt    5  114569.827 ± 41750.603  us/op
[info] CollectionBenchmarks.reduceOptionInline  avgt    5  700196.100 ± 61402.359  us/op
[info] TryBenchmarks.createTry                  avgt    5    1192.911 ±    67.876  us/op
[info] TryBenchmarks.createTryInline            avgt    5    2332.260 ±   326.071  us/op
[info] TryBenchmarks.filter                     avgt    5    1158.533 ±   182.237  us/op
[info] TryBenchmarks.filterInline               avgt    5    1118.867 ±    87.124  us/op
[info] TryBenchmarks.flatMap                    avgt    5    2289.835 ±   130.522  us/op
[info] TryBenchmarks.flatMapInline              avgt    5    4923.598 ±   689.787  us/op
```

I don't know exactly what is going on here, since other than `Try()/inlineTry` macro all look like a wash or are slower.

Some guesses:
1) using the .iterator of a list is worse than the implementations that work directly on the list, so you start in the hole.
2) unexpected interaction with the jit.
3) something buggy about the generated code is still suboptimal.

@ianoc suggested looking at the generated asm code.

Addresses #4

### CODE REVIEW

**Comment by johnynek** [comment]
It looks like `List` does not have an optimized `.iterator`: https://github.com/scala/scala/blob/2.11.x/src/library/scala/collection/immutable/List.scala

I'm not sure which code gets called, but maybe that is pretty suboptimal. That doesn't explain the Try code though.

**Comment by ianoc** [comment]
[info] Result "createTryInline":
[info]   1788.132 ±(99.9%) 13.027 us/op [Average]
[info](min, avg, max) = (1778.736, 1788.132, 1796.299), stdev = 6.813
[info]   CI (99.9%): [1775.105, 1801.158](assumes normal distribution)
[info] 
[info] Secondary result "·asm":
[info] PrintAssembly processed: 44042 total address lines.
[info] Perf output processed (skipped 5.038 seconds):
[info]  Column 1: cycles (9062 events)
[info]  Column 2: instructions (9064 events)
[info] 
[info] ....[Hottest Regions]...............................................................................
[info]   8.70%    7.03%  [0x7fb09100602e:0x7fb0910060bb] in <stub: return entry points>
[info]   5.93%    3.57%  [0x7fb091006209:0x7fb091006296] in <stub: return entry points>
[info]   5.46%    7.35%  [0x7fb09c122c10:0x7fb09c122c6b] in _ZNK8CodeHeap10find_startEPv (libjvm.so)
[info]   5.14%    7.59%  [0x7fb09c19abc0:0x7fb09c19aeb2] in _ZN19java_lang_Throwable19fill_in_stack_traceE6Handle12methodHandleP6Thread (libjvm.so)
[info]   4.97%    4.93%  [0xffffffff8105c93a:0xffffffff8105c93d] in [unknown]([unknown])
[info]   3.64%    5.96%  [0x7fb09c0b7710:0x7fb09c0b7865] in _ZNK5frame6senderEP11RegisterMap (libjvm.so)
[info]   3.59%    4.89%  [0x7fb09bfb35f0:0x7fb09bfb364f] in _ZN9CodeCache9find_blobEPv (libjvm.so)
[info]   3.45%    3.97%  [0x7fb0910174f4:0x7fb091017576] in <stub: irem  112 irem>
[info]   2.56%    3.25%  [0x7fb09101e6c6:0x7fb09101e77b] in <stub: new  187 new>
[info]   2.56%    2.11%  [0x7fb09bf9b5c1:0x7fb09bf9b652] in _ZN15objArrayOopDesc10obj_at_putEiP7oopDesc (libjvm.so)
[info]   2.45%    2.61%  [0x7fb09c19af0b:0x7fb09c19b0a7] in _ZN19java_lang_Throwable19fill_in_stack_traceE6Handle12methodHandleP6Thread (libjvm.so)
[info]   2.12%    0.62%  [0x7fb09101b261:0x7fb09101b350] in <stub: goto  167 goto>
[info]   1.74%    1.99%  [0x7fb09101db23:0x7fb09101dc18] in <stub: invokevirtual  182 invokevirtual>
[info]   1.58%    1.71%  [0x7fb09bfb04c0:0x7fb09bfb04c6] in _ZNK8CodeBlob9is_zombieEv (libjvm.so)
[info]   1.56%    0.71%  [0x7fb09101dd63:0x7fb09101ddfa] in <stub: invokespecial  183 invokespecial>
[info]   1.42%    0.49%  [0x7fb09101dee3:0x7fb09101df86] in <stub: invokestatic  184 invokestatic>
[info]   1.42%    1.13%  [0x7fb09bfb0420:0x7fb09bfb0427] in _ZNK8CodeBlob10is_nmethodEv (libjvm.so)
[info]   1.29%    1.45%  [0x7fb09c19f315:0x7fb09c19f394] in _ZN7oopDesc13obj_field_putEiPS_; _ZN16BacktraceBuilder4pushEP13methodOopDesciP6Thread (libjvm.so)
[info]   1.27%    1.58%  [0x7fb09bf9b790:0x7fb09bf9b7b1] in _ZN19constantPoolOopDesc7slot_atEi (libjvm.so)
[info]   1.19%    1.30%  [0x7fb09c379e40:0x7fb09c379ed9] in _ZN13objArrayKlass8allocateEiP6Thread (libjvm.so)
[info]  37.95%   35.78%  <...other 294 warm regions...>
[info] ....................................................................................................
[info]  99.99%  100.00%  <totals>
[info] 
[info] ....[Hottest Methods (after inlining)]..............................................................
[info]  14.94%   10.75%  <stub: return entry points>
[info]   8.14%   10.56%  _ZN19java_lang_Throwable19fill_in_stack_traceE6Handle12methodHandleP6Thread (libjvm.so)
[info]   5.46%    7.35%  _ZNK8CodeHeap10find_startEPv (libjvm.so)
[info]   5.33%    5.30%  [unknown]([unknown])
[info]   3.88%    6.05%  _ZNK5frame6senderEP11RegisterMap (libjvm.so)
[info]   3.59%    4.89%  _ZN9CodeCache9find_blobEPv (libjvm.so)
[info]   3.45%    3.97%  <stub: irem  112 irem>
[info]   3.12%    3.70%  <stub: new  187 new>
[info]   2.66%    0.93%  <stub: invokespecial  183 invokespecial>
[info]   2.56%    2.11%  _ZN15objArrayOopDesc10obj_at_putEiP7oopDesc (libjvm.so)
[info]   2.42%    2.49%  <stub: invokevirtual  182 invokevirtual>
[info]   2.12%    0.62%  <stub: goto  167 goto>
[info]   2.06%    0.84%  <stub: invokestatic  184 invokestatic>
[info]   1.95%    2.03%  _ZN13objArrayKlass8allocateEiP6Thread (libjvm.so)
[info]   1.58%    1.71%  _ZNK8CodeBlob9is_zombieEv (libjvm.so)
[info]   1.42%    1.13%  _ZNK8CodeBlob10is_nmethodEv (libjvm.so)
[info]   1.40%    0.74%  <stub: getstatic  178 getstatic>
[info]   1.39%    1.59%  _ZN19constantPoolOopDesc7slot_atEi (libjvm.so)
[info]   1.35%    0.14%  <stub: if_icmpeq  159 if_icmpeq>
[info]   1.32%    1.82%  [unknown](perf-1894.map)
[info]  29.83%   31.18%  <...other 117 warm methods...>
[info] ....................................................................................................
[info]  99.99%   99.87%  <totals>
[info] 
[info] ....[Distribution by Area]..........................................................................
[info]  48.82%   58.35%  <native code in (libjvm.so)>
[info]  43.51%   33.34%  <generated code>
[info]   5.33%    5.30%  <native code in ([unknown])>

**Comment by ianoc** [comment]
Moving it to use the non-iterator had about 12% in savings for reduceOption btw, overall a difference of 2.25x vs 2.5x

**Comment by johnynek** [comment]
Should I pick this up from this branch? I want to look at generalizing the iteratation code so we can share between List, using an iterator, and Array.

Also how did you run the benchmarks? Just using run? It looks like parameters I was passing at the command line you were putting in the code, is that right?

**Comment by ianoc** [comment]
Yes, I won't get to do anything else with this likely today/tomorrow and have no outstanding code.

jmh:run -rf csv  -i 8 -wi 5 -f1 -t1 ._CollectionBenchmarks._reduce.*

Is been what i've been using type thing

(8 iterations, 5 warmups, just 1 fork and 1 thread for the reduce benchmarks.)

you should be able to add a -prof stack to run the stackprofiler if its useful too

**Comment by ianoc** [comment]
oh and -rf csv outputs csv output

**Pull request merged**
